export const words: string[] = [
  " ̶p̶r̶o̶c̶r̶a̶s̶t̶i̶n̶a̶t̶i̶o̶n̶",
  " ̶d̶i̶s̶t̶r̶a̶c̶t̶i̶o̶n̶",
  " ̶i̶n̶e̶f̶f̶i̶c̶i̶e̶n̶c̶y̶",
  " ̶i̶n̶c̶o̶n̶s̶i̶s̶t̶e̶n̶c̶y̶",
  " ̶i̶n̶d̶e̶c̶i̶s̶i̶o̶n̶",
  " ̶d̶e̶m̶o̶t̶i̶v̶a̶t̶i̶o̶n̶",
  " ̶p̶r̶o̶c̶r̶a̶s̶t̶i̶n̶a̶t̶i̶o̶n̶",
  " ̶d̶i̶s̶t̶r̶a̶c̶t̶i̶o̶n̶",
  " ̶i̶n̶e̶f̶f̶i̶c̶i̶e̶n̶c̶y̶",
  " ̶i̶n̶c̶o̶n̶s̶i̶s̶t̶e̶n̶c̶y̶",
  " ̶i̶n̶d̶e̶c̶i̶s̶i̶o̶n̶",
  " ̶d̶e̶m̶o̶t̶i̶v̶a̶t̶i̶o̶n̶",
  " ̶p̶r̶o̶c̶r̶a̶s̶t̶i̶n̶a̶t̶i̶o̶n̶",
  " ̶d̶e̶m̶o̶t̶i̶v̶a̶t̶i̶o̶n̶",
  " ̶i̶n̶c̶o̶n̶s̶i̶s̶t̶e̶n̶c̶y̶",
  " ̶d̶i̶s̶t̶r̶a̶c̶t̶i̶o̶n̶",
  " ̶d̶e̶m̶o̶t̶i̶v̶a̶t̶i̶o̶n̶",
  " ̶p̶r̶o̶c̶r̶a̶s̶t̶i̶n̶a̶t̶i̶o̶n̶",
  " ̶d̶e̶m̶o̶t̶i̶v̶a̶t̶i̶o̶n̶",
  " ̶i̶n̶c̶o̶n̶s̶i̶s̶t̶e̶n̶c̶y̶",
  " ̶d̶i̶s̶t̶r̶a̶c̶t̶i̶o̶n̶",
  "Vectr.",
  "focus",  
  "productivity",
  "discipline",
  "persistence",
  "consistency"
];