export const words: string[] = [
  "Vectr",
  "productivity",
  "discipline",
  "persistence",
  "𝚍̶𝚒̶𝚜̶𝚝̶𝚛̶𝚊̶𝚌̶𝚝̶𝚒̶𝚘̶𝚗̶ ",
  "focus",
  "Vectr",
  "productivity",
  "discipline",
  "persistence",
  "𝚍̶𝚒̶𝚜̶𝚝̶𝚛̶𝚊̶𝚌̶𝚝̶𝚒̶𝚘̶𝚗̶ ",
  "focus",
  "Vectr",
  "productivity",
  "discipline",
  "persistence",
  "𝚍̶𝚒̶𝚜̶𝚝̶𝚛̶𝚊̶𝚌̶𝚝̶𝚒̶𝚘̶𝚗̶ ",
  "focus",
  "Vectr",
  "productivity",
  "discipline",
  "persistence",
  "𝚍̶𝚒̶𝚜̶𝚝̶𝚛̶𝚊̶𝚌̶𝚝̶𝚒̶𝚘̶𝚗̶ ",
  "focus",
  "Vectr",
  "productivity",
  "discipline",
  "persistence",
  "𝚍̶𝚒̶𝚜̶𝚝̶𝚛̶𝚊̶𝚌̶𝚝̶𝚒̶𝚘̶𝚗̶ ",
  "focus",
  "Vectr",
  "productivity",
  "discipline",
  "persistence",
  "𝚍̶𝚒̶𝚜̶𝚝̶𝚛̶𝚊̶𝚌̶𝚝̶𝚒̶𝚘̶𝚗̶ ",
  "focus",
  "Vectr",
  "productivity",
  "discipline",
  "persistence",
  "𝚍̶𝚒̶𝚜̶𝚝̶𝚛̶𝚊̶𝚌̶𝚝̶𝚒̶𝚘̶𝚗̶ ",
  "focus",
  "Vectr",
  "productivity",
  "discipline",
  "persistence",
  "𝚍̶𝚒̶𝚜̶𝚝̶𝚛̶𝚊̶𝚌̶𝚝̶𝚒̶𝚘̶𝚗̶ ",
  "focus",
];